config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :categories
 resources :tmpnotices do
    collection do
      post 'indextmp'
      put 'indextmp'
    end
  end
  resources :notices do
   collection do
      post 'indextmp'
      put 'indextmp'
    end
  end
  
  
  resources :cities
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  
  
   root 'notices#index'
  
  get 'sitemap' => 'notices#sitemap'
  get 'tools', to: 'tools#index'
  get 'moderate', to: 'notices#moderation'
  get 'parsing', to: 'parsing#index'
  get 'parse_tmp', to: 'parsing#indextmp', :collection => { :update => :put }
  get 'rules', to: 'notices#rules'
  get 'load_tmp', to: 'parsing#loadtmp'
  get 'listcat', to: 'categories#listcat'
  get 'tags/:tag', to: 'notices#index', as: :tag
  
end

app/models/city.rb
class City < ActiveRecord::Base
has_many :notices
end

app/models/notice.rb
class Notice < ActiveRecord::Base
belongs_to :category
belongs_to :city 
acts_as_taggable


 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#", original: ['500x500>', :jpg] },
  convert_options: { thumb: "-quality 75 -strip", medium: "-quality 75 -strip", original: "-quality 85 -strip" },
 :default_url => "/images/:style/missing.jpg"
  validates_attachment_content_type :avatar, size: { in: 0..500.kilobytes }, :content_type => /\Aimage\/.*\Z/
  has_attached_file :avatar1, :styles => { :medium => "300x300>", :thumb => "100x100#", original: ['500x500>', :jpg] },
  convert_options: { thumb: "-quality 75 -strip", medium: "-quality 75 -strip", original: "-quality 85 -strip" },
 :default_url => "/images/:style/missing.jpg"
  validates_attachment_content_type :avatar1, size: { in: 0..500.kilobytes }, :content_type => /\Aimage\/.*\Z/
  validates :notice, presence: true, length: { minimum: 5, too_short: "мало символов в заголовке" }
  validates :text, presence: true, length: { minimum: 5 }
  
  self.per_page = 40
  
 extend FriendlyId
 friendly_id :notice, use: :slugged
 

 
  
 scope :visible, -> { where :state => "visible" } 
 scope :moderated, -> { where :state => "pending_review" }
 
 def entry_summary(chars=100)
    if summary.blank?
      "#{text[0...chars]}..."
    else
      summary
    end
  end
 
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

 def normalize_friendly_id(string)
    string.to_slug.normalize(transliterations: :russian).to_s
 end

def sitemap
  respond_to do |format|
   format.xml { render file: 'public/sitemaps/sitemap.xml' }
    format.html { redirect_to root_url }
  end
end



 
  def index
   if params[:tag]
    @notices = Notice.tagged_with(params[:tag]).order('created_at DESC').visible.page(params[:page])
   else
   #loa
    if params[:category_id]
     @notices = Notice.where('category_id' => params['category_id']).order('created_at DESC').visible.page(params[:page])
	else
    @notices = Notice.order('created_at DESC').visible.page(params[:page])
   end
  end
  
  end

  def indextmp
  for j in 0..params[:notice_ids].length-1
  i=params[:notice_ids][j].to_i
  @notice = Notice.find(i)
  @cat= Category.find(@notice.category_id)
  @cat.count=@cat.count+1
 
  @cat.save
  end

 Notice.where('id' => params[:notice_ids]).update_all({:state => "visible"})
 Notice.where(:state => 'pending_review').delete_all  
	
  end 
  
  
  
  def show
    @notice = Notice.friendly.find(params[:id])
	#category = Category.all.map { |category| [category.name] }
	#city = City.all.map { |category1| [category1.name] }
    #options_for_select(category_array) 
  end

  def rules
  end
  
  def moderation
   @notices =  Notice.moderated.page(params[:page])
   
  end
  
  def new
  
    @notice = Notice.new
	category = Category.all.map { |category| [category.name] }
	city = City.all.map { |category1| [category1.name] }
    #options_for_select(category_array) 
end
  

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)
	@notice.slug= normalize_friendly_id(@notice.notice)
	if notice_params['category_id'].match('----')
	  s=notice_params['category_id'].delete('----')
	 if  notice_params['category_id'].match('--')
	   s=notice_params['category_id'].delete('--')
	 else
      s=notice_params['category_id']
	 end
	else
	# if  notice_params['category_id'].match('--')
	#   s=notice_params['category_id'].delete('--')
	# else   
      s=notice_params['category_id'] 
	# end 
	end 
 @category = Category.find_by(name: s)
  @notice.category_id= @category.id
	
 if  params[:searchng][:w]!=""
   city=City.new
   city.name= params[:searchng][:w]
   city.save
   city=City.last
   @notice.city_id=city.id
 end
 
    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit!
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
</br>
<%= simple_form_for [ @notice] do |f| %>
  <%= f.error_notification %>

  
       
            <%= f.label "Тема:", class: 'control-label' %>
            <%= f.text_field :notice, class: 'form-control', input_html: { maxlength: 40 }, placeholder: "Не меньше 5 символов" %>
            <%= f.label "Тэги:", class: 'control-label' %>
            <%= f.text_field :tag_list, class: 'form-control',  placeholder: "Тэги вводить через запятую" %>

      
            <%= f.label "Текст объявления:", class: 'control-label' %>
            <%= f.text_area :text, class: 'form-control', rows: 3 , placeholder: "Не меньше 5 символов"%>
      
		</br>
		
		
        <%= f.label "Категория:  ", class: 'control-label' %>
		<%= f.select:category_id do %>
		 <% Category.walk_tree do |c1, level| %>
         <%=  "#{'-'*level}#{c1.name}" %>
        
         
         <%= content_tag(:option, "#{'--'*level}#{c1.name}") %>
       <% end %>
       <% end %>
             </br>
            <%= f.label "Цена:", class: 'control-label' %>
                
		    <%= f.text_field :price, class: 'form-control' %>
        
		
		   <p>* если не числовое значение, то цена=0</p>
            <%= f.association :city, label: "Город: ",  include_blank: true %>
			<p>* если вашего города нет в списке введите его в поле снизу</p>
			<%= simple_fields_for  :searchng do |q| %>
               <%= q.error_notification %>
               <%= q.text_field :w,  class: 'form-control' %>
			   
            <% end %>
        
				
		
            <%= f.label "Автор:", class: 'control-label' %>
            <%= f.text_field :name, class: 'form-control', input_html: { maxlength: 20 } %>
            
		
		
		
            <%= f.label "Email:", class: 'control-label' %>
            <%= f.text_field :email, class: 'form-control', input_html: { maxlength: 20 } %>
        
		
		
		
		
            <%= f.label "Телефон:", class: 'control-label' %>
            <%= f.text_field :phone, class: 'form-control', input_html: { maxlength: 10 } %>
        
		
		</br>
		</br>
	<form class="form-inline" role="form">
     <div class="form-group">
       <%= f.label " Фото:", class: 'col-sm-2 control-label'  %>
       <%= f.file_field :avatar %>
     </div>
      <div class="form-group">
       <%= f.label " Фото:", class: 'col-sm-2 control-label'  %>
       <%= f.file_field :avatar1 %>
     </div>   
     
	</br>
	
	  
            
            <%= f.input :storage_ads, label: "Срок объявления:  ", collection: 30..120, class: 'form-control', input_html: { maxlength: 3 } %>
   
	 
	 
	</br>	
           <%= f.submit 'Запомнить', class: 'btn btn-primary' %>
             
  </form>		
<% end %>

app/views/notices/_form1.html.erb
<%= simple_form_for [@city,@category, @notice] do |f| %>
  <%= f.error_notification %>

  
       
            <%= f.label "Тема:", class: 'control-label' %>
            <%= f.text_field :notice, class: 'form-control', input_html: { maxlength: 60 }, disabled: true %>
      

      
            <%= f.label "Текст объявления:", class: 'control-label' %>
            <%= f.text_area :text, class: 'form-control', rows: 3, disabled: true %>
      
		</br>
		
		 <div class="form-group">
         <%= f.association :category, label: "Категория:  ", class: 'form-control', disabled: true %>
		  </div>
		  <div class="form-group">
         <%= f.association :city,label: "Город:", class: 'form-control', disabled: true %>
         </div>
		

            <%= f.label "Цена:", class: 'control-label' %>
                
		    <%= f.text_field :price, class: 'form-control', disabled: true %>
       
		
            <%= f.label "Автор:", class: 'control-label' %>
            <%= f.text_field :name, class: 'form-control', input_html: { maxlength: 20 }, disabled: true %>
            
		
		
		
            <%= f.label "Email:", class: 'control-label' %>
            <%= f.text_field :email, class: 'form-control', input_html: { maxlength: 20 }, disabled: true %>
        
		
		
		
		
            <%= f.label "Телефон:", class: 'control-label' %>
            <%= f.text_field :phone, class: 'form-control', input_html: { maxlength: 15 }, disabled: true %>
        
		
		</br>
		</br>
	
	<table class="table table-striped table-hover ">

 <thead>
    <tr>
	<th width="45%"></th>
	<th width="45%"></th>
	
     </tr>
  </thead>
  
    <tbody>
 <h4>Фото</h4>
  
 	
    <tr>
     <td>
	 <% if @notice.avatar.url(:original)!=nil %>
	 <div class='icon'><%= image_tag(@notice.avatar.url(:original), class: 'avatar', :size => "500") %></div>
	 </td>
	<% end %>	
	
	  <td>
	 <% if @notice.avatar1.url(:original)!=nil %>
	 <div class='icon'><%= image_tag(@notice.avatar1.url(:original), class: 'avatar', :size => "500" ) %></div>
	 </td>
	 	  
	  <% end %>
   </tr>	
 </tbody>
</table>	
	
 
     
	</br>
	
	  
          <%= f.label "Срок объявления:  ", class: 'control-label' %>
          <%= f.text_field :phone, class: 'form-control', input_html: { maxlength: 3 }, disabled: true %>   
         
	 

             
		
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form' %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<%= javascript_pack_tag 'notice'%>
</br>

<div class="navbar-form navbar-right"><%= link_to 'Дать объявление', new_notice_path, :class => 'btn btn-primary' %></div>
<h5>* все обьявления проходят модерацию...см. Правила</h5>

</br>
</br>

  <%= content_tag :div,
                  id: "notice-form",
                  data: {
                      notices: @notices.to_json(except: [:created_at, :updated_at])
                  } do %>

    <Notice> hello {{ notices }}</Notice>

<% end %>

<!--<table class="table table-striped table-hover ">

 <thead>
    <tr>
	<th width="7%"></th>
	<th width="26%"><center>Объявление</center></th>
    <th width="7"></th>
	<th width="26%"><center>Объявление</center></th>
	 <th width="7%"></th>
	<th width="26%"><center>Объявление</center></th>
     </tr>
  </thead>
  
    <tbody>
 <h4>Последние объявления</h4>
  <%# @notices.each_slice(3) do |a, b, c| %>
 	
    <tr>
     <td>
	 <div class='icon'><%#= image_tag(a.avatar.url(:thumb), class: 'avatar', :size => "80") %></div>
	 </td>
	  
	  
	  <td><h5><%#= link_to h(a.notice), notice_path(a.slug),title: a.notice  %> </h5>
	      <h6><%#= a.entry_summary %> </h6>
		  <h6>Размещено:<%#= a.created_at %></h6>
		  <h6>    Автор: <%#= a.name %></h6>
	  </td>
	
	  <td>
	
	 <%# if b!=nil%>
	 <div class='icon'><%#= image_tag(b.avatar.url(:thumb), class: 'avatar', :size => "80" ) %></div>
	 </td>
	  
	  
	  <td><h4><%#= link_to h(b.notice), notice_path(b.slug), title: b.notice %></h4>
          <h6><%#=  b.entry_summary %> </h6>
		  <h6>Размещено:<%#= b.created_at %>  Автор: <%#= b.name %></h6>
	  </td>
	  
	  <%# end %>
	  
	   <td>
	   <%# if c!=nil%>
	    <div class='icon'><%#= image_tag(c.avatar.url(:thumb), class: 'avatar', :size => "80" ) %></div>
	 </td>
	  
	  
	  <td><h4><%#= link_to h(c.notice), notice_path(c.slug), title: c.notice %></h4>
          <h6><%#= c.entry_summary %> </h6>
		  <h6>Размещено:<%#= c.created_at %>  Автор: <%#= c.name %></h6>
	  </td>
	  
	  <%# end %>
	  
	 </tr>
  <%# end %>
   </tbody>
</table>
<div class="container">
<div class="row">
<div id="tag_cloud" class="col-sm-12" >
  <%# tag_cloud Notice.tag_counts, %w[s m l] do |tag, css_class| %>
    <%#= link_to tag.name, tag_path(tag.name), class: css_class %>
  <%# end %>
</div>
</div>
</div>
 <%#= paginate(@notices) %>
-->

app/views/notices/indextmp.html.erb
</br>
</br>
</br>
</br>
</br>






update...

app/views/notices/moderation.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
<% if current_user.admin %>


 <%= form_tag indextmp_notices_path do %>
<table class="table table-striped table-hover ">

 <thead>
    <tr>
	<th width="10%">Фото</th>
	<th width="48%">Объявление</th>
	<th width="10%">Имя</th>
	<th width="10%">Имейл</th>
	<th width="10%">фон</th>
	<th width="2%"></th>
   
     </tr>
  </thead>
  
    <tbody>
 <h4>Последние объявления</h4>
  <% @notices.each do |a| %>
 	
    <tr>
     <td>
	 <div class='icon'><%= image_tag(a.avatar.url(:thumb), class: 'avatar', :size => 15) %></div>
	 </td>
	  
	  
	  <td><h4><%= link_to h(a.notice), notice_path(a.id) %> </h4>
	      <h6><%= link_to h(a.text), notice_path(a.id) %> </h6>
	  </td>
	  
	 <td><h6><%= a.name %> </h6> </td>
	<td><h6><%= a.email %> </h6> </td>
	<td><h6><%= a.phone %> </h6> </td>
	<td> 
	 
	    <%= check_box_tag "notice_ids[]", a.id %> 
	  
	  </td>
	  
	 </tr>
  <% end %>
   </tbody>
</table>
<%= submit_tag "Загрузить в базу ...." %>
 <% end %>
  
 <%= paginate(@notices) %>
 
<% end %>
<% end %>

app/views/notices/new.html.erb
<h1>Новое Объявление</h1>

<%= render 'form' %>

<%= link_to 'Назад', notices_path %>

app/views/notices/rules.html.erb
</br>
</br>
</br>
</br>




<h3>Правила</h3></br>
<p4>на доске запрещается: </p4></br>
<li>- размещать объявление криминального, националистического или порнографического характера;</li>
<li>- размещать сообщения, порочащие честь и достоинство третьих лиц;</li>
<li>- размещать фотографии порнографического характера;</li>
<li>- подача объявлений, содержащих ненормативную лексику и нарушающие нормы морали;</li>
<li>- подача объявления без указания данных для обратной связи (емайл, телефон или URL);</li>
<li>- размещать одно и то же объявление в разные разделы;</li>
<li>- размещать объявление, содержание которого не соответствует теме выбранного раздела;</li>
<li>- размещать сообщения общего рекламного характера, сообщения не соответствующие тематике раздела.</li>
<li>- в тексте обьявления размещать ссылки на сторонние ресурсы.</li>

<h3>В случае нарушения правил, Ваше объявление не будет размещено.</h3></br> 
</br> 
<p4>Администрация сайта никоим образом не несёт ответственность за услуги или товар,</br>
предложение которых находится на данной доске, а также оставляет за собой право не размещать</br>
любое объявление без объяснения причин.</p4>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<meta name="viewport" content="initial-scale=1, maximum-scale=1" />
<% content_for :title, @notice.notice %>

<%= render 'form1'  %>
 
		
          
	
 </br>
</br> 
<script type="text/javascript" src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js" charset="utf-8"></script>
<script type="text/javascript" src="//yastatic.net/share2/share.js" charset="utf-8"></script>
<div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,moimir,gplus,twitter,evernote,linkedin,viber,whatsapp"></div>
  


<% if user_signed_in? %>
<% if current_user.admin %>
<%= link_to 'Редактировать', edit_notice_path(@notice) %> |
<% end %>
<% end %>
<%= link_to 'Назад', notices_path %>