config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :categories
 resources :tmpnotices do
    collection do
      post 'indextmp'
      put 'indextmp'
    end
  end
  resources :notices do
   collection do
      post 'indextmp'
      put 'indextmp'
    end
  end
  
  
  resources :cities
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  
  
   root 'notices#index'
  
  get 'sitemap' => 'notices#sitemap'
  get 'tools', to: 'tools#index'
  get 'moderate', to: 'notices#moderation'
  get 'parsing', to: 'parsing#index'
  get 'parse_tmp', to: 'parsing#indextmp', :collection => { :update => :put }
  get 'rules', to: 'notices#rules'
  get 'load_tmp', to: 'parsing#loadtmp'
  get 'listcat', to: 'categories#listcat'
  get 'tags/:tag', to: 'notices#index', as: :tag
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
		  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#",original: ['500x500>', :jpg] }, :default_url => "/images/:style/anonyme.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    
  end
  
  def create
    
	@user = User.find(params[:topic_id])
    
	
	@user.count_message=0	
	@user.save
	
    respond_to do |format|
      if @user.save
        PffMailer.welcome_email(@user).deliver_now
        format.html { redirect_to topic_path(@topic.id), notice: 'User was successfully created.' }
        #format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

 # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Вход", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Регистрация", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Забыли пароль?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>