config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :categories
 resources :tmpnotices do
    collection do
      post 'indextmp'
      put 'indextmp'
    end
  end
  resources :notices do
   collection do
      post 'indextmp'
      put 'indextmp'
    end
  end
  
  
  resources :cities
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  
  
   root 'notices#index'
  
  get 'sitemap' => 'notices#sitemap'
  get 'tools', to: 'tools#index'
  get 'moderate', to: 'notices#moderation'
  get 'parsing', to: 'parsing#index'
  get 'parse_tmp', to: 'parsing#indextmp', :collection => { :update => :put }
  get 'rules', to: 'notices#rules'
  get 'load_tmp', to: 'parsing#loadtmp'
  get 'listcat', to: 'categories#listcat'
  get 'tags/:tag', to: 'notices#index', as: :tag
  
end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :notices, :dependent => :destroy
acts_as_tree
extend ActsAsTree::TreeWalker

  acts_as_tree order: 'name'
  

 
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  def listcat
   @categories = Category.all
  end
  
  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit!
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  
<div class="field">
    <%= f.label :parent_id %><br>
    <%= f.collection_select(:parent_id,  Category.order(:name), :id, :name, :include_blank => true) %>
   
  </div>
  
  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  
 

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

 <h1>Listing Categories</h1>
 <%= link_to 'New Category', new_category_path %>
 
 <table>
   <thead>
     <tr>
       <th>Parent</th>
 	  <th>Name</th>
       <th colspan="3"></th>
     </tr>
   </thead>
 
   <tbody>
     <% @categories.each do |category| %>
       <tr>
 	    <td><%= category.parent_id %></td>
         <td><%= category.name %></td>
         <td><%= link_to 'Show', category %></td>
         <td><%= link_to 'Edit', edit_category_path(category) %></td>
         <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
     <% end %>
   </tbody>
 </table>
 
 <br>

app/views/categories/listcat.html.erb
<p id="notice"><%= notice %></p>

<h1>Категории</h1>
 <% for cat in Category.roots %>
   
	
      <li><h3><%=  link_to cat.name, notices_path(category_id: cat.id) %> <%= cat.count%></h3></li>
	


<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th></th>
	  <th></th>
	  <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
 
    <% cat.children.each_slice(3) do |a,b,c| %>
      <tr>
	    
        <td><h4><%= link_to a.name, notices_path(category_id: a.id) %>  <%= a.count%></h4>
		<%  a.children.each do |cat1| %>
          <h5><%= link_to cat1.name, notices_path(category_id: cat1.id) %>  <%= cat1.count%></h5>
		<% end %>  </td>
		
		<% if b!=nil%>
		 <td><h4><%= link_to b.name, notices_path(category_id: b.id) %>  <%= b.count%></h4>
		 <%  b.children.each do |cat1| %>
          <h5><%= link_to cat1.name, notices_path(category_id: cat1.id) %>  <%= cat1.count%></h5>
		 <% end %> </td> 
		<% end %>  
		
		 <% if c!=nil%>
		  <td><h4><%= link_to c.name, notices_path(category_id: c.id) %>  <%= c.count%></h4>
		<%  c.children.each do |cat1| %>
          <h5><%= link_to cat1.name, notices_path(category_id: cat1.id) %>  <%= cat1.count%></h5>
		 <% end %>  </td>
		<% end %>   
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>