config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :categories
 resources :tmpnotices do
    collection do
      post 'indextmp'
      put 'indextmp'
    end
  end
  resources :notices do
   collection do
      post 'indextmp'
      put 'indextmp'
    end
  end
  
  
  resources :cities
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  
  
   root 'notices#index'
  
  get 'sitemap' => 'notices#sitemap'
  get 'tools', to: 'tools#index'
  get 'moderate', to: 'notices#moderation'
  get 'parsing', to: 'parsing#index'
  get 'parse_tmp', to: 'parsing#indextmp', :collection => { :update => :put }
  get 'rules', to: 'notices#rules'
  get 'load_tmp', to: 'parsing#loadtmp'
  get 'listcat', to: 'categories#listcat'
  get 'tags/:tag', to: 'notices#index', as: :tag
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Add this to <head> -->
  <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap/dist/css/bootstrap.min.css"/>
  <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.css"/>

  <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
  <link href="https://unpkg.com/vuetify/dist/vuetify.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">



   <title><%= yield :title %> | Доска объявлений </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>

</head>
<body>

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>


<div id="app">
  <b-navbar  type="light" variant="white" toggleable>


    <b-navbar-brand ><%= link_to "Блошиная ДОСКА", root_path, class: 'navbar-brand' %></b-navbar-brand>

      <b-navbar-nav>
        <b-nav-item variant="white"><%= link_to " Категории", listcat_path %></b-nav-item>
        <b-nav-item ><%= link_to "Правила", rules_path %></b-nav-item>
        <b-nav-item ><%= link_to 'Поиск', root_path %></b-nav-item>
      </b-navbar-nav>
        <b-collapse is-nav id="nav_dropdown_collapse" right>

        <!-- Navbar dropdowns -->


          <b-navbar-nav class="ml-auto">

          <% if user_signed_in? %>
              <b-nav-item ><%= link_to current_user.name, edit_user_registration_path %></b-nav-item>
              <b-nav-item ><%= link_to 'Выход', destroy_user_session_path, method: :delete %></b-nav-item>
              <b-nav-item-dropdown text="Админ" right>
                <b-dropdown-item ><%= link_to 'Posts', notices_path %></b-dropdown-item>
                <b-dropdown-item ><%= link_to 'Администратор', rails_admin_path %></b-dropdown-item>
                <b-dropdown-item ><%= link_to 'Категории', categories_path %></b-dropdown-item>
                <b-dropdown-item ><%= link_to 'Tools', tools_path %></b-dropdown-item>
                <b-dropdown-item ><%= link_to 'Модерация', moderate_path %></b-dropdown-item>
              </b-nav-item-dropdown>



          <% else %>
              <b-dropdown-item ><%= link_to 'Вход', new_user_session_path %></b-dropdown-item>
              <b-dropdown-item ><%= link_to 'Регистрация', new_user_registration_path %></b-dropdown-item>
          <% end %>



      </b-navbar-nav>
        </b-collapse>

  </b-navbar>


  <div class="container ">
    <div class="right">
    <b-tabs>
      <b-tab title="first" active>
        <br>I'm the first fading tab
      </b-tab>
      <b-tab title="second">
        <br>I'm the second tab content
      </b-tab>
      <b-tab title="disabled">
        <br>Disabled tab!
      </b-tab>
    </b-tabs>
  </div>
  </div>




</div>




<div class="container">
  <% for cat in Category.roots %>
    <button type="button" class="btn btn-default">
	<ul>
      <li><%= link_to h(cat.name), listcat_path %></li>
	</ul>
	</button>
  <% end %>
  </div>


		
	</div>


	      <div class="container">
              <%= yield %>
          </div>


<script src="//unpkg.com/babel-polyfill@latest/dist/polyfill.min.js"></script>
<script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js"></script>
<script src="https://unpkg.com/vuetify/dist/vuetify.js"></script>

</body>

<footer class="footer">
<div class="panel-footer nav navbar-nav navbar-left">
<h4>По всем вопросам обращаться:     <mailto:>paukoffru@yandex.ru</h4>
 </div>
<div class="panel-footer nav navbar-nav navbar-right">

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter35180180 = new Ya.Metrika({
                    id:35180180,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/35180180" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

 <!-- HotLog -->
<span id="hotlog_counter"></span>
<span id="hotlog_dyn"></span>
<script type="text/javascript">
var hot_s = document.createElement('script');
hot_s.type = 'text/javascript'; hot_s.async = true;
hot_s.src = 'http://js.hotlog.ru/dcounter/2520265.js';
hot_d = document.getElementById('hotlog_dyn');
hot_d.appendChild(hot_s);
</script>
<noscript>
<a href="http://click.hotlog.ru/?2520265" target="_blank"><img
src="http://hit34.hotlog.ru/cgi-bin/hotlog/count?s=2520265&amp;im=304" border="0"
alt="HotLog"></a>
</noscript>
<!-- /HotLog -->


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-73428039-1', 'auto');
  ga('send', 'pageview');

</script>

<!-- Rating@Mail.ru counter -->
<script type="text/javascript">
var _tmr = window._tmr || (window._tmr = []);
_tmr.push({id: "2742280", type: "pageView", start: (new Date()).getTime()});
(function (d, w, id) {
  if (d.getElementById(id)) return;
  var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true; ts.id = id;
  ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
  var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
  if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
})(document, window, "topmailru-code");
</script><noscript><div style="position:absolute;left:-10000px;">
<img src="//top-fwz1.mail.ru/counter?id=2742280;js=na" style="border:0;" height="1" width="1" alt="Рейтинг@Mail.ru" />
</div></noscript>
<!-- //Rating@Mail.ru counter -->
<!-- Rating@Mail.ru logo -->
<a href="http://top.mail.ru/jump?from=2742280">
<img src="//top-fwz1.mail.ru/counter?id=2742280;t=479;l=1" 
style="border:0;" height="31" width="88" alt="Рейтинг@Mail.ru" /></a>
<!-- //Rating@Mail.ru logo -->

<!-- begin of Top100 code -->

<script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?4405549"></script>
<noscript>
<a href="http://top100.rambler.ru/navi/4405549/">
<img src="http://counter.rambler.ru/top100.cnt?4405549" alt="Rambler's Top100" border="0" />
</a>

</noscript>
<!-- end of Top100 code -->


</div>
</footer>
</html>